on: [push]

name: WVD Deployment

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    env:
       subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1
       resource_group_name: rg-wvd
       location: Australia East
    environment:
       name: staging
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Resource Group
      uses: Azure/cli@1.0.4
      with:        
        inlineScript: |
          az group create --name hub-spoke --location "Australia East"
          az deployment group create \
              --resource-group hub-spoke \
              --template-uri https://raw.githubusercontent.com/mspnp/samples/master/solutions/azure-hub-spoke/azuredeploy.json \
              --parameters adminUserName=Melcloudadmin adminPassword=Password2020! linuxVMCount=1 windowsVMCount=1

