on: 
  push:
    branches:
      - main


name: WVD Deployment

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    env:
       subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1       
    environment:
       name: staging
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Resource Group
      uses: Azure/cli@1.0.4
      with:        
        inlineScript: |
          az deployment group create \
          --resource-group hub-spoke \
          --template-file  ./arm-remplates/azuredeploy1.json \
          --parameters adminUserName=Melcloudadmin adminPassword=Password2020! linuxVMCount=0 windowsVMCount=1
         
