name: BicepAzcli



on:
 push:
   branches:
     - main
 
env:
  subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1
  resource_group_name: rg-stg-learn
  location: Australia East

jobs:
  bicepAzCliDeploy:
   name: Bicep AZ CLI Deploy job
   runs-on: ubuntu-latest
   env:
    location: Australia East
   

   steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Deploy  Resource Group 
      uses: Azure/cli@1.0.4
      with:
        inlinescript: |
         az deployment sub create \
         --name ${{env.resource_group_name }} \
         --location "${{ env.location}}" \
         --template-file ./bicep-templates/resourcedeploy.bicep \
         --parameters \
         resourceGroupName=${{ env.resource_group_name }} \
         location="${{ env.location}}"

    - name: Deploy  virtual network
      uses: Azure/cli@1.0.4
      with:
         inlinescript: |
            az deployment group create \
             --resource-group ${{ env.resource_group_name }} \
             --template-file ./bicep-templates/vnet.bicep \
             --parameters \
             vnetName="hub-vnet" \
             vnetAddressPrefix="10.10.0.0/16" \
             subnet1Prefix ="10.10.1.0/24" \
             subnet1Name=web \
             subnet2Prefix="10.10.2.0/24" \
             subnet2Name=workload \
             subnet3Prefix="10.10.3.0/24" \
             subnet3Name=AzureBastionSubnet \
             subnet4Prefix="10.10.4.0/24" \
             subnet4Name=AzureFirewallSubnet \
             subnet5Prefix="10.10.5.0/24" \
             subnet5Name=ApplicationGatewaySubnet \
             subnet6Prefix="10.10.6.0/24" \
             subnet6Name=GatewaySubnet \
             location ="${{ env.location}}" 

   