name: BicepAzcli



on:
 push:
   branches:
     - main
 
env:
  subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1
  location: Australia East

jobs:
  bicepAzCliDeploy:
   name: Bicep AZ CLI Deploy job
   runs-on: ubuntu-latest
   env:
    location: Australia East
   

   steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Deploy  Resource Group 
      uses: Azure/cli@1.0.4
      with:
        inlinescript: |
         az deployment sub create \
         --name ${{env.resource_group_name }} \
         --location "${{ env.location}}" \
         --template-file ./bicep-templates/resourcedeploy.bicep \
         --parameters \
         resourceGroupName=${{ env.resource_group_name }} \
         location="${{ env.location}}"

   