<<<<<<< HEAD
name: "Bicep Deploy WorkFlow"

on:
  push:
    branches:
      - main
 
env:

  subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1

jobs:
    bicepAzCliDeploy:
      name: Bicep AZ CLI Deploy job
      runs-on: ubuntu-latest
      env:
       resource_group_name: rg-bicp-azcli-githubactions
       location: Australia East

      steps:
        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }} 

        - name: Deploy  Resource Group 
          uses: Azure/cli@1.04
          with:
            inlinescript: |
             az deployment sub create \
             --name ${{env.resource_group_name }} \
             --location "${{ env.location}}" \
             --template-file ./bicep-templates/resourcegroup.bicep \
             --parameters \
             resourceGroupName=${{ env.resource_group_name }} \
             location="${{ env.location}}"

        - name: Deploy  virtual network
          uses: Azure/cli@1.04
          with:
            inlinescript: |
             az deployment group create \
             --resource-group ${{ env.resource_group_name }} \
             --template-file ./bicep-templates/virtualnetwork.bicep \
             --parameters \
             vNetPrefix=bicepazcli \
             location ="${{ env.location}}"               
             
             
 
    bicepArmDeployAction:
      name: Bicep arm-deploy Deploy job
      runs-on: ubuntu-latest
      env:
       resource_group_name: rg-bicp-armdeploy-githubactions
       location: Australia East

      steps:
        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }} 

        - name: Deploy  Resource Group 
          uses: Azure/arm-deploy@v1
          with:
           scope: subscription
           subscriptionId : ${{env.subscriptionId}}
           region: "${{env.location}}"
           template: ./bicep-templates/resourcegroup.bicep
           parameters:
            location="${{env.location}}"
            resourceGroupName=${{env.resource_group_name}}
          

        - name: Deploy  vnet
          uses: Azure/arm-deploy@v1
          with:
           scope: resourcegroup
           resourceGroupName: ${{env.resource_group_name}}
           subscriptionId : ${{env.subscriptionId}}
           template: ./bicep-templates/virtualnetwork.bicep
           parameters:
            vNetPrefix=biceparmdeploy
            location="${{env.location}}"
            
=======
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
>>>>>>> 141df53bf687f0cd7966178eac667d36020ca533
