name: Bicep



#on:
  #push:
    #branches:
      #- main
 
env:
  subscriptionId: 0268ad35-91f4-4596-a9ee-70245667e9d1
  location: Australia East

jobs:
  bicepArmDeployAction:         
   name: Bicep arm-deploy Deploy job
   runs-on: ubuntu-latest
   env:
     location: Australia East

   steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Deploy  Resource Group 
      uses: Azure/arm-deploy@v1
      with:
       scope: subscription
       subscriptionId : ${{env.subscriptionId}}
       region: "${{env.location}}"
       template: ./bicep-templates/resourcegroup.bicep
       parameters:
         location="${{env.location}}"
         resourceGroupName=${{env.resource_group_name}}
       deploymentMode : incremental
          

    - name: Deploy  vnet
      uses: Azure/arm-deploy@v1
      with:
       scope: resourcegroup
       resourceGroupName: ${{env.resource_group_name}}
       subscriptionId : ${{env.subscriptionId}}
       template: ./bicep-templates/virtualnetwork.bicep
       parameters:
        vNetPrefix=biceparmdeploy
        location="${{env.location}}"
       deploymentMode : incremental

    - name: Deploy  Storage Account
      uses: Azure/arm-deploy@v1
      id: storageAccountDeploy
      with:
        scope: resourcegroup
        resourceGroupName : ${{env.resource_group_name}}
        subscriptionId : ${{env.subscriptionId}}
        template: ./bicep-templates/storage.bicep
        parameters: 
         location="${{env.location}}"
        deploymentMode : incremental

    - name: Deploy  Virtual Machine
      uses: Azure/arm-deploy@v1      
      with:
        scope: resourcegroup
        resourceGroupName : ${{env.resource_group_name}}
        subscriptionId : ${{env.subscriptionId}}
        template: ./bicep-templates/virtualmachine.bicep
        parameters: 
         vmname = simple-vm
         adminPassword = '[parameters('adminPassword')]'
         location="${{env.location}}"
        deploymentMode : incremental




    
            


